openapi: 3.0.3
info:
  title: Nutrients Calculator Web App - REST API Service
  description: >-
    This is a REST API service for the Nutrients Calculator Web App. This service provides the ability to calculate the nutrients of a food item based on the user's input.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:8080
tags:
  - name: calculations
    description: Endpoints for nutrient calculations
paths:
  /calculations:
    summary: List all calculations
    get:
      summary: List all calculations
      operationId: ListAllCalculations
      tags:
        - calculations
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StringArray"
    post:
      summary: Insert a new calculation
      operationId: SetNewCalculation
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid request body
      tags:
        - calculations
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/KeyValue"

  /calculations/{uuid}:
    summary: Get calculation by UUID
    get:
      tags:
        - calculations
      summary: Get calculation by UUID
      operationId: GetCalculationByUUID
      parameters:
        - name: uuid
          in: path
          description: UUID of calculation to return
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KeyValue"
        "404":
          description: UUID not found
    delete:
      tags:
        - calculations
      summary: Delete calculation by UUID
      description: Deletes a single calculation based on the UUID supplied
      operationId: DeleteCalculationByUUID
      parameters:
        - name: uuid
          in: path
          description: UUID of calculation to delete
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
        "404":
          description: Calculation not found
  /healthz:
    summary: Healthcheck endpoint
    get:
      summary: Healthcheck
      operationId: Healthcheck
      responses:
        "200":
          description: Healthy response

components:
  schemas:
    Key:
      type: object
      properties:
        uuid:
          type: string
          example: "my-uuid"
    Status:
      type: object
      properties:
        status:
          type: string
          example: "read"
    KeyValue:
      type: object
      required:
        - title
        - author
        - status
      properties:
        title:
          type: string
          example: "my-title"
        author:
          type: string
          example: "my-author"
        status:
          type: string
          example: "read"
    StringArray:
      type: array
      items:
        type: string
